### ISSUE TITLE
The number of topics in kafka control center did not increase

### ISSUE THREAD

**Issue by topefolorunso** [ankurchavda/streamify#6]
After creating docker container for the kafka instance and running the script to send message to it with the eventsim, the number of topics in the control center (9021) would not increase. I remained at 40.

Notice the warning at the top. What could that mean please?

![jwKsvLXT jpg large](https://user-images.githubusercontent.com/66448986/170806794-f054f9d0-48ad-4acf-a156-aaf6b7a5f39e.jpg)

**Comment by ankurchavda** [comment]
Hey, can you share some more details about this? Unable to understand what exactly is wrong.
