### ISSUE TITLE
how much will cost on the whole to complete this project?

### ISSUE THREAD

**Issue by spurthi-dantu** [ankurchavda/streamify#9]
I have 300 free tier credits currently, will they be enough to get done with this project

**Comment by ankurchavda** [comment]
Yes, should be enough

**Comment by spurthi-dantu** [comment]
Okay, Thank you so much for the info. Also I am new to data engineering and
I am using my vs code in local machine to complete the project, will there
be any problem? If yes please tell me how to create a VM and run on it?

**Comment by spurthi-dantu** [comment]
Thank you so much, th project is very helpful
